name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --cache ~/.npm --prefer-offline --no-audit --production
      - name: Build the project
        run: npm run build --if-present
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          skip-install: true
          args: 'chrome qa-testing/tests/ -e -a "npm run dev" --app-init-delay 1000 --hostname localhost'
